-----------------CRIAÇÃO DE INDICES
CREATE INDEX i_COMMITER_HASH ON ISSUES (COMMITER_HASH);
CREATE INDEX i_COMMITER_HASH_SONAR ON ISSUES_sonar (commit_hash);
CREATE INDEX i_COMMITER_HASH ON [ISSUES_SONAR] ([commit_hash])

alter table [ISSUES_SONAR] add IDF BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1)

